# Generated by Django 4.2.8 on 2026-04-07 03:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('organization', models.CharField(default='FlowPilot Inc', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Superadmin'), ('team_leader', 'Team Leader'), ('senior_dev', 'Senior Developer'), ('junior_dev', 'Junior Developer'), ('intern', 'Intern')], default='intern', help_text='User role for permission management', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.team'),
        ),
    ]
