# Generated by Django 4.2.8 on 2026-04-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_team_join_request'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamjoinrequest',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='team',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
